name: record_linux
description: Stub package for record_linux to fix compilation issues on Windows/Android builds
version: 0.7.2
homepage: https://github.com/llfbandit/record

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: RecordLinuxPlugin

dependencies:
  flutter:
    sdk: flutter
  record_platform_interface: ^1.4.0
